### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by ZeroDot1** [xd4rker/MinerBlock#11]
Please remove `bplaced.net` 
bplaced is a Feehosting Service

**Comment by xd4rker** [comment]
One of its subdomains is hosting cryptojacking scripts `piti.bplaced.net`
https://publicwww.com/websites/%22piti.bplaced.net%22/

**Comment by ZeroDot1** [comment]
OK, thanks for the information.

Please add it like this,
`*://piti.bplaced.net/*`
This prevents errors.

**Comment by xd4rker** [comment]
I think we should blacklist the whole domain until we make sure it's not been hacked. I'm waiting for their feedback on this.

**Comment by ZeroDot1** [comment]
The domain was not hacked, but there are several malware on some subdomains. 
https://www.virustotal.com/de/ip-address/94.130.236.100/information/

**Comment by xd4rker** [comment]
I forgot the fact that they provide free subdomains, my bad XD
I will blacklist `piti.bplaced.net` as you suggested, Thanks!

**Comment by ZeroDot1** [comment]
Thank you :+1:
