### ISSUE TITLE
Invalid hosts

### ISSUE THREAD

**Issue by ZeroDot1** [xd4rker/MinerBlock#13]
```
cryweb.github.io
crywebber.github.io
piti.bplaced.net
```
See: 
https://twitter.com/bplaced/status/960907873596387328
https://twitter.com/bad_packets/status/960667587423043584

**Comment by xd4rker** [comment]
Thanks!

Looks like they switched to `msg-2[.]me` and `cryptown[.]netlify.com` as a replacement for `piti[.]bplaced.net`. Check here http://www.crypto-webminer.com/integrate.html

**Comment by ZeroDot1** [comment]
Thanks for the information :)
