### ISSUE TITLE
New Miner 

### ISSUE THREAD

**Issue by ZeroDot1** [xd4rker/MinerBlock#14]
```
whathyx.com
pan.whathyx.com
ewtuyytdf45.com
pon.ewtuyytdf45.com
```
https://www.virustotal.com/de/ip-address/164.132.200.121/information/

**Comment by ZeroDot1** [comment]
https://www.virustotal.com/de/ip-address/195.154.102.23/information/

**Comment by ZeroDot1** [comment]
https://www.virustotal.com/de/ip-address/165.227.78.12/information/

**Comment by ZeroDot1** [comment]
https://www.virustotal.com/de/domain/freecontent.bid/information/
https://www.virustotal.com/de/ip-address/85.17.26.67/information/

**Comment by xd4rker** [comment]
Thanks for reporting these ones, will take a look at them.
