### ISSUE TITLE
New Miner

### ISSUE THREAD

**Issue by ZeroDot1** [xd4rker/MinerBlock#15]
https://pastebin.com/d5yr2tcm

**Comment by xd4rker** [comment]
Thanks, will check it out

**Comment by menzow** [comment]
This is not a new miner. They use a reverse proxy to redirect the `/proxy.js` request to the coin-hive script. This bypasses blocks set at a DNS level. I checked and minerBlock (v1.1.11) successfully detects the script and blocks it.

**Comment by xd4rker** [comment]
Here is the deobfuscated script: https://pastebin.com/PBrjAaKS

As @menzow said, MinerBlock already detects it. Adding `wss://*.zlx.com.br/*` as a filter just in case :)

Thanks gain!
