### ISSUE TITLE
New Miner

### ISSUE THREAD

**Issue by petemahon** [xd4rker/MinerBlock#16]
Salon.com have introduced opt-in mining. MinerBlock doesn't detect or block the activity.  

Is MinerBlock designed to allow opt-in mining?

Thanks.

**Comment by petemahon** [comment]
Added filter for worker.salon.com

**Comment by xd4rker** [comment]
Yes, MinerBlock was designed to block miners that run without the user's knowledge or consent.
I'm merging your PR because salon.com seem to be forcing the users to opt-in, which is not cool :/

Thanks again!
