### ISSUE TITLE
The extension crashes upon accessing the assets URL

### ISSUE THREAD

**Issue by motatest** [xd4rker/MinerBlock#19]
If you try to go to the following URL:

chrome-extension://emikbbbebcdfohonlaifafnoanocnebl/assets/

The extension crashes and needs to be repaired (Chrome will do that by redownloading and reinstalling it).

Note: you might need to access "MinerBlock filters" text file link first from the settings page, "My Filters" tap if the URL I provided doesn't do the crash for you.

**Comment by xd4rker** [comment]
I think this bug is more related to Chrome rather than MinerBlock. I tested with other extensions and they all crashed when accessing a folder URL. I will dig into it more to see what causes it. Thank you!

**Comment by xd4rker** [comment]
Closing this as it has been fixed in Chrome 66.0.3359.139.
