### ISSUE TITLE
Suspicious activity on tron.network

### ISSUE THREAD

**Issue by menzow** [xd4rker/MinerBlock#25]
When I visit https://tron.network/ chrome reports over 1.5Gb of GPU being used.  Not sure if it's just their ridiculous banner being extremely inefficient or they're actually loading parts of their blockchain into visitors browsers.

minerBlock didn't pick up anything but might be worth checking it out.

**Comment by xd4rker** [comment]
Thanks for reporting this! I think it's from the extensive animations on the banner.

![](https://i.imgur.com/QgoZbct.png)
