### ISSUE TITLE
Are these correct ?

### ISSUE THREAD

**Issue by thunderpants** [xd4rker/MinerBlock#28]
I'm getting "blocked miner" warnings for these 3 sites:

`https://www.steamgifts.com/`
`http://www.opiumpulses.com`
`https://www.vanillavapes.co.uk`

Block is for :
Mineralt (inline)

I've been told that one of them ,"steamgifts" ,doesn't have miners running on it but minerBlock says different .
Could it be a bug or is it definitely true that they do have a miner ?

I have multiple tabs open in my waterfox browser with many websites and just these 3 sites are coming up with that miner warning.

Is it possible that these sites could have been "hijacked" in some way without the website owners being aware of it ?

I've run multiple security scans of my computer using a winpe disc and everything comes back clear.

edit:
I was thinking it might be a bug in that checkbox in the settings for showing how many miners have been blocked overall.
I have it switched on but it doesn't always show on all sites ,sometimes it show nothing and other times it says '1'  .

**Comment by thunderpants** [comment]
I think i will close this ,i have a feeling the "warnings" are not warnings per se
but  because i have the box checked in settings that shows a tally of how many miners have been blocked overall.

**Comment by xd4rker** [comment]
Hi, thanks for reporting this. I have tested the websites on Waterfox 56.2.2 (64-bit) and none of them gave a warning. I don't think this can be a false positive because it has already been fixed in #21.
Do you mind sharing the HTML code of one of those pages?
