### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by ghajini** [xd4rker/MinerBlock#3]
As title ,pls build firefox extension of MinerBlock , as firefox is improving with webextensions  .....

**Comment by xd4rker** [comment]
The work on FF extension is in progress. It shall be available the next week.
Thank you!

**Comment by Emilylove00** [comment]
Still not FF extension?!

**Comment by xd4rker** [comment]
@Emilylove00 Apologies for the delay, I've been kinda busy lately... I'll do my best to release it ASAP.

**Comment by Emilylove00** [comment]
Great! i am using nocoin right now but i want to try your extension because i saw that you keep updating more often.

**Comment by btric-development** [comment]
Awesome! I switched to Firefox because it seems to be a little more private than Chrome, "made for people, not profit".  So having this add-on for Firefox will be great.

**Comment by xd4rker** [comment]
Sorry for the long wait! Firefox add-on is available here : https://addons.mozilla.org/en-US/firefox/addon/minerblock-origin/
