### ISSUE TITLE
Firefox extension: minerkill.js file gets downloaded when you use the Firefox save page feature.

### ISSUE THREAD

**Issue by pbgnz** [xd4rker/MinerBlock#33]
Firefox version: Firefox Quantum (64 bit)
OS: Ubuntu 18.04 LTS

Problem:
When you use download certain pages using the Firefox "Save Page As..." feature, the minerkiller.js file gets saved to the assets folder.

Demo steps to reproduce bug:
1- Open Firefox
2- Go to https://www.utdallas.edu/~mxk055100/courses/
3- Right click the page and select the "Save Page As..." option
4- Select the location to download the page (ex: Downloads)
5- Open the location of chosen above (ex: Downloads)
6- select the assets folder of the page (ex: Teaching_files)
7- the minerkill.js file will be there

**Comment by xd4rker** [comment]
Hi, thanks for reporting this!
I think this bug is more related to Firefox as it should prevent extension assets to get downloaded like Chrome does. MinerBlock needs to inject minerkill.js on each page you visit, and I don't think there is a way to fix this on the extension level.

**Comment by xd4rker** [comment]
I'll be closing this. Please feel free to re-open if necessary.
