### ISSUE TITLE
Do we need this add-on in Firefox 68?

### ISSUE THREAD

**Issue by sphh** [xd4rker/MinerBlock#40]
The new Firefox 68.0 has the possibility to block cryptominers: https://support.mozilla.org/en-US/kb/content-blocking

Could you please explain if (and why) we still need the MinerBlock add-on. Thanks!

**Comment by xd4rker** [comment]
I'm not sure if the blocking in the new Firefox is only based on a blacklist, but MinerBlock uses two different methods for the blocking. It blocks calls to mining domains, then scans the page's DOM for any potential mining code. Have a look here for more details: https://github.com/xd4rker/MinerBlock#how-does-it-work

If Firefox is combining these two methods for the blocking (and uses a better blacklist), then I think there is no need to use MinerBlock anymore :)

**Comment by sphh** [comment]
Well, according to https://blog.mozilla.org/firefox/block-cryptominers-with-firefox/, the built-in cryptominer blocking uses a list:

> To help you combat these unwelcome scripts, we’ve partnered with Disconnect and compiled lists of domains that serve cryptomining scripts so you can block them directly through Firefox. Open the Firefox preferences menu, select “Privacy & Security.” Blocking cryptomining is as easy as clicking the box.
