### ISSUE TITLE
Doubt with your filter

### ISSUE THREAD

**Issue by gallegonovato** [xd4rker/MinerBlock#53]
Good afternoon:

First of all I wanted to thank you for your work and time. And for all your help.

I wanted to ask you a question about your https://raw.githubusercontent.com/xd4rker/MinerBlock/master/assets/filters.txt filter.

Would this be valid and effective for ublock origin as well.

Best regards

**Comment by xd4rker** [comment]
Hi @gallegonovato, yes it should also work for ublock origin :)

**Comment by gallegonovato** [comment]
Good afternoon::

First of all let me thank you again for your time, effort and help. 

And apologize for taking so long to respond. But I was with family problems and it was impossible for me to answer you before. Please excuse me. 

Thank you very much for the clarification and added this to ublock.

Thanks a million for all your work and effort and help.

**Comment by xd4rker** [comment]
Glad to help. I will be closing this then :)
