### ISSUE TITLE
Question about filter

### ISSUE THREAD

**Issue by sanatg** [xd4rker/MinerBlock#55]
HI @xd4rker i was modifying the minerblock code for to me used as an adblocker with a custom compiled block list of 70,000 plus domains but it is slowing down the browsing speeds and some times freezes the browser significantly so is there a way to integrate that whole list without any significant effect on performance.

thanks in advance.

**Comment by xd4rker** [comment]
Hi @sanatg, sorry for the late reply!

MinerBlock was not designed to block Ads, please use [uBlock](https://github.com/gorhill/uBlock) instead.

**Comment by sanatg** [comment]
> Hi @sanatg, sorry for the late reply!
> 
> MinerBlock was not designed to block Ads, please use [uBlock](https://github.com/gorhill/uBlock) instead.

Ok thanks no problem @xd4rker
